### ISSUE TITLE
Re-export SDL types

### ISSUE THREAD

**Issue by rfuest** [embedded-graphics/simulator#14]
The `SimulatorEvent` enum uses 3 types from the `sdl2` crate for mouse and keyboard events. To use these values in another crate an dependency to the correct version of the `sdl2` must be added. If the `simulator` crate would re-export the SDL types it would be easier to use these values without requiring another dependency.

**Comment by jamwaffles** [comment]
I've thought about doing this for a while, so it's a :+1: from me.
