### ISSUE TITLE
Remove tinytga and tinybmp dependencies

### ISSUE THREAD

**Issue by rfuest** [embedded-graphics/simulator#18]
This crate currently still depends on the tinytga for `generate-drawing-examples`, which can cause dependency problems. We need to move `generate-drawing-examples` to somewhere else to fix this.

**Comment by jamwaffles** [comment]
It's a shame we can't just relegate them to `dev-dependencies` :thinking:.

We could move the generator into a sub-crate of this repo I suppose. It would be good to keep all the code in `simulator` as it's very specific to the docs here.

**Comment by rfuest** [comment]
I would like to move the `generate-drawing-examples` stuff into the main `embedded-graphics` repo, because the `docs` directory should also be in that repo. But there is already another open issue about this problem: https://github.com/embedded-graphics/embedded-graphics/issues/462

**Comment by rfuest** [comment]
Closed by #21
