### ISSUE TITLE
Simulator version 0.2.1 disappeared

### ISSUE THREAD

**Issue by rfuest** [embedded-graphics/simulator#2]
While testing `embedded-fonts` I encountered some problems when I wanted to add a dependency to the simulator.

The latest ZIP release correctly sets version to `0.2.1` in the simulator `Cargo.toml` and also contains a changelog section for that version. But the master doesn't contain any of these changes and I'm not sure how that happened.

**Comment by jamwaffles** [comment]
Some light digging:

- Changelog: `0.2.0`
- crates.io: `0.2.1`
- `master` branch Cargo.toml: `0.2.0`

Still not sure what happened :grimacing:
