### ISSUE TITLE
New alpha release

### ISSUE THREAD

**Issue by rfuest** [embedded-graphics/simulator#23]
A new alpha release should allow us to get rid of some git dependencies.

**Comment by jamwaffles** [comment]
`0.3.0-alpha.2`, right?

**Comment by jamwaffles** [comment]
0.3.0-alpha.2 is out

**Comment by rfuest** [comment]
I don't think there will be many changes in the simulator until the `0.7` release, so we could also call it `beta.1`. I don't have a preference for one or the other, just pick the one you like.

**Comment by rfuest** [comment]
Thanks

**Comment by jamwaffles** [comment]
Ahhh too slow, sorry, but yes we're getting close :)
