### ISSUE TITLE
Simulate color screens: bypass mapping to b/w

### ISSUE THREAD

**Issue by lrbalt** [embedded-graphics/simulator#27]
- Version of embedded-graphics-simulator in use (if applicable): 0.2.1
- Version of embedded-graphics in use (if applicable): 0.6.2

## Description of the problem/feature request/other

I am trying to simulate a tri-color e-paper display (black/white/chromatic). The simulator translates all colors using `BinaryColorTheme` in `src/theme/rs` to two colors. Therefore I cannot show three colors.

Are you open for a PR that adds a `Passthrue` to the enum that bypasses the `map_color` function?

**Comment by rfuest** [comment]
The default `BinaryColorTheme::Default` should already pass the colors through unaltered. Or to be more precise: It uses the output of the `Into<Rgb888>` impl for your color type.

**Comment by lrbalt** [comment]
How did I miss that. That is exactly what I meant. Completely overlooked this. Sorry for that.
