### ISSUE TITLE
Yanked indirect dependencies

### ISSUE THREAD

**Issue by bugadani** [embedded-graphics/simulator#36]
While publishing e-t, I got the following warnings:

```
warning: package `bytemuck v1.7.0` in Cargo.lock is yanked in registry `crates-io`, consider updating to a version that is not yanked
warning: package `crossbeam-deque v0.8.0` in Cargo.lock is yanked in registry `crates-io`, consider updating to a version that is not yanked
```

According to `cargo tree`, these are dependencies of `image`:
```
├── embedded-graphics-simulator v0.3.0
│   ├── base64 v0.13.0
│   ├── embedded-graphics v0.7.1 (*)
│   ├── image v0.23.14
│   │   ├── bytemuck v1.7.0
│   │   ├── byteorder v1.4.3
│   │   ├── color_quant v1.1.0
│   │   ├── gif v0.11.2
│   │   │   ├── color_quant v1.1.0
│   │   │   └── weezl v0.1.5
│   │   ├── jpeg-decoder v0.1.22
│   │   │   └── rayon v1.5.1
│   │   │       ├── crossbeam-deque v0.8.0
```

IMO simulator should upgrade to a newer version if `image` once it becomes available.

**Comment by bugadani** [comment]
Nah I'm dumb this doesn't need any changes.

**Comment by jamwaffles** [comment]
Do you know what caused the original warnings, and what did you do to fix them?

**Comment by bugadani** [comment]
So the build system tries to find the most recent dependency that matches what's in all the Cargo.tomls, and so a cargo update can properly figure out that it can use the newer versions.

crossbeam had a race condition bug and was yanked because of that
bytemuck had a soundness bug and has been yanked

I guess for a moment I got confused by the warnings and assumed those versions would be baked in my crate. But that's not the case.
