### ISSUE TITLE
Start using sdl2 "bundled" feature by default

### ISSUE THREAD

**Issue by elimerl** [embedded-graphics/simulator#54]
- Version of embedded-graphics-simulator in use (if applicable): 0.6.0
- Version of embedded-graphics in use (if applicable): 0.8.1

## Description of the problem/feature request/other

Because embedded-graphics-simulator is probably going to be used for debugging, consider enabling the "bundled" feature on the sdl2 crate by default. This would simplify builds for most users of the library, especially on Windows where installing C libraries is somewhat annoying. For production people might want to use a dynamically linked version of SDL but I don't think that's relevant for this library for debugging. You can also just expose the feature as default on and allow user to disable it.

**Comment by rfuest** [comment]
I had suggested this before, but was told by Windows users that setting up a compiler would be more hassle than installing the SDL library: https://github.com/embedded-graphics/embedded-graphics/pull/388

**Comment by elimerl** [comment]
Oh ok, I didn't see the previous issue. Thanks.
