### ISSUE TITLE
Remove use of chaining from examples

### ISSUE THREAD

**Issue by rfuest** [embedded-graphics/simulator#7]
The `analog-clock` example uses chaining, which breaks hardware acceleration. Should we change it to instead pass a `DrawTarget` to the `draw_...` functions?

**Comment by jamwaffles** [comment]
That would probably be a good idea.

**Comment by rfuest** [comment]
There are two more examples that use chaining `primitive-strokes` and `chaining`. How should we handle these?

Do we need a `chaining` example if this isn't recommended in most use cases and not supported by all drawables? Or should we keep the example and document these limitations?

**Comment by jamwaffles** [comment]
We could probably remove all the chaining examples tbh. I'd still like to demonstrate it in some small way, but that could perhaps be in various doc comments in e-g instead of full examples in the simulator.
